### ISSUE TITLE
bug! shallow copy in fetch events

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/dataportal#98]
Hey @tacaswell found a super fun bug due to a shallow copy in fetch events.  See this notebook:
http://nbviewer.ipython.org/gist/anonymous/748df99a8cfdb809fc96

(also because its an ipython notebook, there's an implicit `git fetch @danielballan`)

p.s. really wanted to title this issue `git fetch @tacaswell`

**Comment by tacaswell** [comment]
Why is fetch_events mutating the input like that?

**Comment by danielballan** [comment]
Thanks for the detailed bug report.

@tacaswell, `mds.find_event` expects something with an `id` attribute. Headers combine IDs for Run Start and Run End, and hence have `run_start_id`, not `id`. My intention was to copy the Header, set the expected `id` attribute, and then pass it to `find_event`. Because I chose `copy` instead of `deepcopy`, the original was mutated.

I would prefer to add `find_events_from_headers` to MDS, something that expects object(s) with `run_start_id` attributes. The only safe alternative is to `deepcopy` the Header and mutate it.
